### ISSUE TITLE
Update Worker deployment for SaaS

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-chaos#485]
When running experiments in SaaS we expect some taints for deployments otherwise they can't schedule correctly or at least this causes issues with scheduling, see for the details in this thread https://camunda.slack.com/archives/CQZGZ882Z/p1706103587782179

We have to add the following:

Taint
```
NoSchedule:components.gke.io/camunda-managed-components=true
```

```
# Required to schedule a pod on this node pool
tolerations:
- effect: NoSchedule
  key: components.gke.io/camunda-managed-components
  operator: Equal
  value: "true"
```

See details https://github.com/camunda-cloud/team-sre/blob/main/docs/gke_taints_tolerations.md
